apiVersion: v1
kind: ConfigMap
metadata:
  name: azuredrop-config
  namespace: azuredrop
data:
  NODE_ENV: "production"
  PORT: "5000"

  POSTGRES_DB: "azuredrop"
  POSTGRES_USER: "azuredrop"

  DATABASE_SSL: "false"
  DATABASE_SSL_REJECT_UNAUTHORIZED: "true"

  JWT_EXPIRES_IN: "24h"

  CORS_ORIGINS: "http://192.168.49.2:30080"
  PUBLIC_BASE_URL: "http://192.168.49.2:30080"

  MAX_FILE_SIZE_MB: "10"

  SHARE_DEFAULT_EXPIRY_MINUTES: "60"
  SHARE_MAX_EXPIRY_MINUTES: "10080"

  AZURE_STORAGE_CONTAINER_NAME: "azuredrop-files"
  AZURE_STORAGE_PUBLIC_BLOB_ENDPOINT: "http://192.168.49.2:30080/blob/devstoreaccount1"
